name: Generate Build

on:
  workflow_call:

jobs:
  package:
    needs: [ instrumentation-test ]
    name: Generate Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.7

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk