name: Test debug

on:
  workflow_call:

jobs:
  unit-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.7

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Cache gradle
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: true

#      - name: Android Test Report
#        uses: asadmansr/android-test-report-action@v1.2.0


      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Test Reporter with PR Comment
        uses: n-ryu/test-reporter@v0.0.2
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.html'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results