name: Cancel Previous Job

on:
  workflow_call:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: cancel
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{github.token}}