name: On Pull Request or Push Called

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    uses: ./.github/workflows/job_lint.yml

  test:
    needs: [lint]
    uses: ./.github/workflows/job_test.yml