name: On Pull Request or Push Called

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cancel:
    name: Cancel Previous Workflow
    permissions:
      actions: write
    uses: ./.github/workflows/job_cancel_previous.yml

  lint:
    needs: [cancel]
    name: Lint
    uses: ./.github/workflows/job_lint.yml

  test:
    needs: [lint]
    name: Test
    uses: ./.github/workflows/job_test.yml